"""Versioned schema migrations (applied by ``app.db.migrate``). Add a new version at the end; never edit an applied one."""

# Version 1 = the original MAVE tables. Every later version is a list of single statements applied once,
# each version inside its own transaction (PostgreSQL DDL is transactional, so a failing step leaves the
# database exactly at the previous version).
#
# Timestamps are Unix epoch seconds in DOUBLE PRECISION columns, as they always were.
MIGRATIONS: dict[int, list[str]] = {
    1: [
        """CREATE TABLE users(
             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             email TEXT UNIQUE NOT NULL,
             salt BYTEA NOT NULL,
             pw_hash BYTEA NOT NULL,
             created_at DOUBLE PRECISION NOT NULL
           )""",
        """CREATE TABLE history(
             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
             query TEXT NOT NULL,
             ts DOUBLE PRECISION NOT NULL,
             UNIQUE(user_id, query)
           )""",
        """CREATE TABLE saved(
             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
             url TEXT NOT NULL,
             title TEXT NOT NULL,
             snippet TEXT NOT NULL DEFAULT '',
             thumbnail TEXT,
             ts DOUBLE PRECISION NOT NULL,
             UNIQUE(user_id, url)
           )""",
        """CREATE TABLE query_log(
             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             query TEXT NOT NULL,
             ts DOUBLE PRECISION NOT NULL
           )""",
        "CREATE INDEX idx_qlog_ts ON query_log(ts)",
        """CREATE TABLE documents(
             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             url TEXT UNIQUE NOT NULL,
             domain TEXT NOT NULL,
             title TEXT NOT NULL,
             body TEXT NOT NULL,
             lang TEXT,
             fetched_at DOUBLE PRECISION NOT NULL
           )""",
        "CREATE INDEX idx_docs_domain ON documents(domain)",
        """CREATE TABLE link_counts(
             url TEXT PRIMARY KEY,
             n INTEGER NOT NULL DEFAULT 0
           )""",
        """CREATE TABLE frontier(
             url TEXT PRIMARY KEY,
             depth INTEGER NOT NULL,
             status TEXT NOT NULL DEFAULT 'pending',
             added_at DOUBLE PRECISION NOT NULL
           )""",
        "CREATE INDEX idx_frontier_status ON frontier(status, depth, added_at)",
    ],
    2: [  # accounts: e-mail verification, rotating sessions, password reset, preferences
        "ALTER TABLE users ADD COLUMN email_verified INTEGER NOT NULL DEFAULT 0",
        """CREATE TABLE sessions(
             id TEXT PRIMARY KEY,
             user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
             refresh_hash TEXT NOT NULL UNIQUE,
             prev_hash TEXT,
             created_at DOUBLE PRECISION NOT NULL,
             rotated_at DOUBLE PRECISION NOT NULL,
             expires_at DOUBLE PRECISION NOT NULL,
             revoked_at DOUBLE PRECISION
           )""",
        "CREATE INDEX idx_sessions_user ON sessions(user_id)",
        "CREATE INDEX idx_sessions_prev ON sessions(prev_hash)",
        """CREATE TABLE password_resets(
             token_hash TEXT PRIMARY KEY,
             user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
             created_at DOUBLE PRECISION NOT NULL,
             expires_at DOUBLE PRECISION NOT NULL,
             used_at DOUBLE PRECISION
           )""",
        "CREATE INDEX idx_resets_user ON password_resets(user_id)",
        """CREATE TABLE email_verifications(
             token_hash TEXT PRIMARY KEY,
             user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
             created_at DOUBLE PRECISION NOT NULL,
             expires_at DOUBLE PRECISION NOT NULL,
             used_at DOUBLE PRECISION
           )""",
        "CREATE INDEX idx_verif_user ON email_verifications(user_id)",
        """CREATE TABLE user_preferences(
             user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
             lang TEXT,
             theme TEXT
           )""",
    ],
    3: [  # crawler v1.0: priority/retry frontier, canonical URL, duplicate fingerprints, recrawl schedule
        "ALTER TABLE frontier ADD COLUMN priority DOUBLE PRECISION NOT NULL DEFAULT 0",
        "ALTER TABLE frontier ADD COLUMN attempts INTEGER NOT NULL DEFAULT 0",
        "ALTER TABLE frontier ADD COLUMN next_at DOUBLE PRECISION NOT NULL DEFAULT 0",
        "ALTER TABLE frontier ADD COLUMN last_error TEXT",
        "CREATE INDEX idx_frontier_pick ON frontier(status, next_at, priority)",
        "ALTER TABLE documents ADD COLUMN canonical_url TEXT",
        "ALTER TABLE documents ADD COLUMN content_hash TEXT",
        "ALTER TABLE documents ADD COLUMN simhash BIGINT",
        "ALTER TABLE documents ADD COLUMN crawl_interval DOUBLE PRECISION",
        "ALTER TABLE documents ADD COLUMN next_crawl_at DOUBLE PRECISION",
        "CREATE INDEX idx_docs_hash ON documents(content_hash)",
        "CREATE INDEX idx_docs_next_crawl ON documents(next_crawl_at)",
        """CREATE TABLE simhash_bands(
             band INTEGER NOT NULL,
             value INTEGER NOT NULL,
             doc_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE
           )""",
        "CREATE INDEX idx_simhash_bands ON simhash_bands(band, value)",
        "CREATE INDEX idx_simhash_doc ON simhash_bands(doc_id)",  # PostgreSQL does not index foreign keys itself
    ],
    4: [  # admin dashboard: managed crawl seeds + audit log of administrative actions
        """CREATE TABLE seeds(
             url TEXT PRIMARY KEY,
             enabled INTEGER NOT NULL DEFAULT 1,
             added_at DOUBLE PRECISION NOT NULL
           )""",
        """CREATE TABLE audit_log(
             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             ts DOUBLE PRECISION NOT NULL,
             actor TEXT NOT NULL,
             action TEXT NOT NULL,
             detail TEXT NOT NULL DEFAULT ''
           )""",
        "CREATE INDEX idx_audit_ts ON audit_log(ts)",
    ],
    5: [  # search: PostgreSQL full-text search replaces SQLite FTS5
        # unaccent is a "trusted" extension: the database owner may create it without being a superuser.
        "CREATE EXTENSION IF NOT EXISTS unaccent SCHEMA public",
        # unaccent() is only STABLE; an IMMUTABLE wrapper is required to use it in an indexed/generated column.
        """CREATE FUNCTION mave_unaccent(text) RETURNS text
             LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT
             AS $$ SELECT public.unaccent('public.unaccent'::regdictionary, $1) $$""",
        # Title weighs more than body (weights are applied at ranking time, see app/index.py).
        """ALTER TABLE documents ADD COLUMN tsv tsvector GENERATED ALWAYS AS (
             setweight(to_tsvector('simple', mave_unaccent(coalesce(title, ''))), 'A') ||
             setweight(to_tsvector('simple', mave_unaccent(coalesce(body, ''))), 'B')
           ) STORED""",
        "CREATE INDEX idx_docs_tsv ON documents USING GIN (tsv)",
        # Spelling vocabulary: one row per indexed term with the number of documents containing it.
        """CREATE MATERIALIZED VIEW docs_vocab AS
             SELECT word AS term, ndoc AS cnt FROM ts_stat('SELECT tsv FROM documents')""",
        "CREATE UNIQUE INDEX idx_docs_vocab_term ON docs_vocab(term)",  # also required by REFRESH ... CONCURRENTLY
        "CREATE INDEX idx_docs_vocab_prefix ON docs_vocab(term text_pattern_ops)",  # fast LIKE 'abc%'
    ],
    6: [  # admin user management: an account can be disabled (NULL = active) without deleting its data
        "ALTER TABLE users ADD COLUMN disabled_at DOUBLE PRECISION",
    ],
    7: [  # user-level admin authorization: role 'user' (default) or 'admin' (see app/api/deps.py)
        "ALTER TABLE users ADD COLUMN role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin'))",
    ],
}
